const WORDS_NL = {
  easy: [
    { word: "kat", category: "Dieren", hint: "Dit dier spint en miauut" },
    { word: "hond", category: "Dieren", hint: "De beste vriend van de mens" },
    { word: "vis", category: "Dieren", hint: "Leeft in het water" },
    { word: "koe", category: "Dieren", hint: "Geeft melk" },
    { word: "aap", category: "Dieren", hint: "Klimt graag in bomen" },
    { word: "boom", category: "Natuur", hint: "Groeit in het park" },
    { word: "zon", category: "Natuur", hint: "Schijnt overdag" },
    { word: "maan", category: "Natuur", hint: "Zie je 's nachts" },
    { word: "brood", category: "Eten", hint: "Eet je bij het ontbijt" },
    { word: "melk", category: "Eten", hint: "Wit drankje van de koe" },
    { word: "bal", category: "Speelgoed", hint: "Rond en rolt" },
    { word: "pop", category: "Speelgoed", hint: "Poppetje om mee te spelen" },
    { word: "fiets", category: "Vervoer", hint: "Heeft twee wielen" },
    { word: "auto", category: "Vervoer", hint: "Rijdt op de weg" },
    { word: "boot", category: "Vervoer", hint: "Vaart op het water" },
  ],
  medium: [
    { word: "vlinder", category: "Dieren", hint: "Heeft kleurrijke vleugels" },
    {
      word: "schildpad",
      category: "Dieren",
      hint: "Draagt zijn huis op zijn rug",
    },
    { word: "giraf", category: "Dieren", hint: "Heeft een lange nek" },
    { word: "olifant", category: "Dieren", hint: "Grootste landdier" },
    { word: "pinguin", category: "Dieren", hint: "Leeft op de Zuidpool" },
    { word: "appel", category: "Eten", hint: "Rood of groen fruit" },
    { word: "banaan", category: "Eten", hint: "Geel en krom fruit" },
    { word: "wortel", category: "Eten", hint: "Oranje groente" },
    {
      word: "kasteel",
      category: "Gebouwen",
      hint: "Woonden vroeger koningen in",
    },
    { word: "school", category: "Gebouwen", hint: "Hier leer je elke dag" },
    { word: "regenboog", category: "Natuur", hint: "Verschijnt na de regen" },
    { word: "vulkaan", category: "Natuur", hint: "Berg die vuur spuugt" },
    { word: "trein", category: "Vervoer", hint: "Rijdt op rails" },
    { word: "vliegtuig", category: "Vervoer", hint: "Vliegt door de lucht" },
    { word: "raket", category: "Vervoer", hint: "Gaat naar de ruimte" },
  ],
  hard: [
    {
      word: "krokodil",
      category: "Dieren",
      hint: "Gevaarlijk reptiel met scherpe tanden",
    },
    {
      word: "neushoorn",
      category: "Dieren",
      hint: "Heeft een hoorn op zijn neus",
    },
    {
      word: "bibliotheek",
      category: "Gebouwen",
      hint: "Hier kun je boeken lenen",
    },
    {
      word: "chocolade",
      category: "Eten",
      hint: "Lekker zoet, gemaakt van cacao",
    },
    { word: "spaghetti", category: "Eten", hint: "Lange dunne pasta" },
    { word: "magneet", category: "Wetenschap", hint: "Trekt metaal aan" },
    {
      word: "telescoop",
      category: "Wetenschap",
      hint: "Kijk daarmee naar de sterren",
    },
    {
      word: "microscoop",
      category: "Wetenschap",
      hint: "Maakt kleine dingen groot",
    },
    {
      word: "waterval",
      category: "Natuur",
      hint: "Water dat naar beneden valt",
    },
    { word: "woestijn", category: "Natuur", hint: "Droog en heet landschap" },
    { word: "piraat", category: "Verhalen", hint: "Zoekt schatten op zee" },
    { word: "draak", category: "Verhalen", hint: "Fabeldier dat vuur spuugt" },
    { word: "tovenaar", category: "Verhalen", hint: "Kan magische trucjes" },
    { word: "ridder", category: "Verhalen", hint: "Beschermt het kasteel" },
    { word: "zeemeermin", category: "Verhalen", hint: "Half mens, half vis" },
  ],
  expert: [
    { word: "dolfijn", category: "Dieren", hint: "Slim zeezoogdier" },
    { word: "kameleon", category: "Dieren", hint: "Verandert van kleur" },
    {
      word: "archeoloog",
      category: "Beroepen",
      hint: "Graaft naar oude voorwerpen",
    },
    { word: "astronaut", category: "Beroepen", hint: "Gaat naar de ruimte" },
    { word: "dirigent", category: "Beroepen", hint: "Leidt een orkest" },
    { word: "vulkanoloog", category: "Beroepen", hint: "Bestudeert vulkanen" },
    {
      word: "fotosynthese",
      category: "Wetenschap",
      hint: "Hoe planten voedsel maken met licht",
    },
    {
      word: "evenwicht",
      category: "Wetenschap",
      hint: "Alles staat in balans",
    },
    { word: "regenwormen", category: "Natuur", hint: "Leven in de grond" },
    { word: "paradijs", category: "Natuur", hint: "Een plek als de hemel" },
    {
      word: "expeditie",
      category: "Avontuur",
      hint: "Een grote ontdekkingsreis",
    },
    {
      word: "schatkist",
      category: "Avontuur",
      hint: "Daarin bewaren piraten goud",
    },
    { word: "labyrint", category: "Avontuur", hint: "Een ingewikkeld doolhof" },
    { word: "tijdmachine", category: "Avontuur", hint: "Reizen door de tijd" },
    {
      word: "planetarium",
      category: "Wetenschap",
      hint: "Gebouw waar je sterren bekijkt",
    },
  ],
};
