const WORDS_NL = {
  easy: [
    { word: 'kat',   category: 'Dieren',    hint: 'Dit dier spint en miauut' },
    { word: 'hond',  category: 'Dieren',    hint: 'De beste vriend van de mens' },
    { word: 'vis',   category: 'Dieren',    hint: 'Leeft in het water' },
    { word: 'koe',   category: 'Dieren',    hint: 'Geeft melk' },
    { word: 'aap',   category: 'Dieren',    hint: 'Klimt graag in bomen' },
    { word: 'boom',  category: 'Natuur',    hint: 'Groeit in het park' },
    { word: 'zon',   category: 'Natuur',    hint: 'Schijnt overdag' },
    { word: 'maan',  category: 'Natuur',    hint: "Zie je 's nachts" },
    { word: 'brood', category: 'Eten',      hint: 'Eet je bij het ontbijt' },
    { word: 'melk',  category: 'Eten',      hint: 'Wit drankje van de koe' },
    { word: 'bal',   category: 'Speelgoed', hint: 'Rond en rolt' },
    { word: 'pop',   category: 'Speelgoed', hint: 'Poppetje om mee te spelen' },
    { word: 'fiets', category: 'Vervoer',   hint: 'Heeft twee wielen' },
    { word: 'auto',  category: 'Vervoer',   hint: 'Rijdt op de weg' },
    { word: 'boot',  category: 'Vervoer',   hint: 'Vaart op het water' },
  ],
  medium: [
    { word: 'vlinder',   category: 'Dieren',    hint: 'Heeft kleurrijke vleugels' },
    { word: 'schildpad', category: 'Dieren',    hint: 'Draagt zijn huis op zijn rug' },
    { word: 'giraf',     category: 'Dieren',    hint: 'Heeft een lange nek' },
    { word: 'olifant',   category: 'Dieren',    hint: 'Grootste landdier' },
    { word: 'pinguin',   category: 'Dieren',    hint: 'Leeft op de Zuidpool' },
    { word: 'appel',     category: 'Eten',      hint: 'Rood of groen fruit' },
    { word: 'banaan',    category: 'Eten',      hint: 'Geel en krom fruit' },
    { word: 'wortel',    category: 'Eten',      hint: 'Oranje groente' },
    { word: 'kasteel',   category: 'Gebouwen',  hint: 'Woonden vroeger koningen in' },
    { word: 'school',    category: 'Gebouwen',  hint: 'Hier leer je elke dag' },
    { word: 'regenboog', category: 'Natuur',    hint: 'Verschijnt na de regen' },
    { word: 'vulkaan',   category: 'Natuur',    hint: 'Berg die vuur spuugt' },
    { word: 'trein',     category: 'Vervoer',   hint: 'Rijdt op rails' },
    { word: 'vliegtuig', category: 'Vervoer',   hint: 'Vliegt door de lucht' },
    { word: 'raket',     category: 'Vervoer',   hint: 'Gaat naar de ruimte' },
  ],
  hard: [
    { word: 'krokodil',    category: 'Dieren',     hint: 'Gevaarlijk reptiel met scherpe tanden' },
    { word: 'neushoorn',   category: 'Dieren',     hint: 'Heeft een hoorn op zijn neus' },
    { word: 'bibliotheek', category: 'Gebouwen',   hint: 'Hier kun je boeken lenen' },
    { word: 'chocolade',   category: 'Eten',       hint: 'Lekker zoet, gemaakt van cacao' },
    { word: 'spaghetti',   category: 'Eten',       hint: 'Lange dunne pasta' },
    { word: 'magneet',     category: 'Wetenschap', hint: 'Trekt metaal aan' },
    { word: 'telescoop',   category: 'Wetenschap', hint: 'Kijk daarmee naar de sterren' },
    { word: 'microscoop',  category: 'Wetenschap', hint: 'Maakt kleine dingen groot' },
    { word: 'waterval',    category: 'Natuur',     hint: 'Water dat naar beneden valt' },
    { word: 'woestijn',    category: 'Natuur',     hint: 'Droog en heet landschap' },
    { word: 'piraat',      category: 'Verhalen',   hint: 'Zoekt schatten op zee' },
    { word: 'draak',       category: 'Verhalen',   hint: 'Fabeldier dat vuur spuugt' },
    { word: 'tovenaar',    category: 'Verhalen',   hint: 'Kan magische trucjes' },
    { word: 'ridder',      category: 'Verhalen',   hint: 'Beschermt het kasteel' },
    { word: 'zeemeermin',  category: 'Verhalen',   hint: 'Half mens, half vis' },
  ],
  expert: [
    { word: 'dolfijn',      category: 'Dieren',     hint: 'Slim zeezoogdier' },
    { word: 'kameleon',     category: 'Dieren',     hint: 'Verandert van kleur' },
    { word: 'archeoloog',   category: 'Beroepen',   hint: 'Graaft naar oude voorwerpen' },
    { word: 'astronaut',    category: 'Beroepen',   hint: 'Gaat naar de ruimte' },
    { word: 'dirigent',     category: 'Beroepen',   hint: 'Leidt een orkest' },
    { word: 'vulkanoloog',  category: 'Beroepen',   hint: 'Bestudeert vulkanen' },
    { word: 'fotosynthese', category: 'Wetenschap', hint: 'Hoe planten voedsel maken met licht' },
    { word: 'evenwicht',    category: 'Wetenschap', hint: 'Alles staat in balans' },
    { word: 'regenwormen',  category: 'Natuur',     hint: 'Leven in de grond' },
    { word: 'paradijs',     category: 'Natuur',     hint: 'Een plek als de hemel' },
    { word: 'expeditie',    category: 'Avontuur',   hint: 'Een grote ontdekkingsreis' },
    { word: 'schatkist',    category: 'Avontuur',   hint: 'Daarin bewaren piraten goud' },
    { word: 'labyrint',     category: 'Avontuur',   hint: 'Een ingewikkeld doolhof' },
    { word: 'tijdmachine',  category: 'Avontuur',   hint: 'Reizen door de tijd' },
    { word: 'planetarium',  category: 'Wetenschap', hint: 'Gebouw waar je sterren bekijkt' },
  ],
};

const WORDS_EN = {
  easy: [
    { word: 'cat',   category: 'Animals',   hint: 'This animal purrs and meows' },
    { word: 'dog',   category: 'Animals',   hint: "Man's best friend" },
    { word: 'fish',  category: 'Animals',   hint: 'Lives in water' },
    { word: 'cow',   category: 'Animals',   hint: 'Gives milk' },
    { word: 'frog',  category: 'Animals',   hint: 'Jumps and says ribbit' },
    { word: 'tree',  category: 'Nature',    hint: 'Grows in the park' },
    { word: 'sun',   category: 'Nature',    hint: 'Shines during the day' },
    { word: 'moon',  category: 'Nature',    hint: 'You see it at night' },
    { word: 'bread', category: 'Food',      hint: 'You eat it at breakfast' },
    { word: 'milk',  category: 'Food',      hint: 'White drink from a cow' },
    { word: 'ball',  category: 'Toys',      hint: 'Round and rolls' },
    { word: 'doll',  category: 'Toys',      hint: 'A small figure to play with' },
    { word: 'bike',  category: 'Transport', hint: 'Has two wheels' },
    { word: 'car',   category: 'Transport', hint: 'Drives on the road' },
    { word: 'boat',  category: 'Transport', hint: 'Floats on water' },
  ],
  medium: [
    { word: 'butterfly', category: 'Animals',   hint: 'Has colourful wings' },
    { word: 'turtle',    category: 'Animals',   hint: 'Carries its house on its back' },
    { word: 'giraffe',   category: 'Animals',   hint: 'Has a very long neck' },
    { word: 'elephant',  category: 'Animals',   hint: 'Largest land animal' },
    { word: 'penguin',   category: 'Animals',   hint: 'Lives at the South Pole' },
    { word: 'apple',     category: 'Food',      hint: 'Red or green fruit' },
    { word: 'banana',    category: 'Food',      hint: 'Yellow and curved fruit' },
    { word: 'carrot',    category: 'Food',      hint: 'Orange vegetable' },
    { word: 'castle',    category: 'Buildings', hint: 'Kings used to live here' },
    { word: 'school',    category: 'Buildings', hint: 'You learn here every day' },
    { word: 'rainbow',   category: 'Nature',    hint: 'Appears after the rain' },
    { word: 'volcano',   category: 'Nature',    hint: 'Mountain that spits fire' },
    { word: 'train',     category: 'Transport', hint: 'Runs on rails' },
    { word: 'airplane',  category: 'Transport', hint: 'Flies through the air' },
    { word: 'rocket',    category: 'Transport', hint: 'Goes to outer space' },
  ],
  hard: [
    { word: 'crocodile',  category: 'Animals',   hint: 'Dangerous reptile with sharp teeth' },
    { word: 'rhinoceros', category: 'Animals',   hint: 'Has a horn on its nose' },
    { word: 'library',    category: 'Buildings', hint: 'You can borrow books here' },
    { word: 'chocolate',  category: 'Food',      hint: 'Sweet treat made from cacao' },
    { word: 'spaghetti',  category: 'Food',      hint: 'Long thin pasta' },
    { word: 'magnet',     category: 'Science',   hint: 'Attracts metal objects' },
    { word: 'telescope',  category: 'Science',   hint: 'Use it to look at stars' },
    { word: 'microscope', category: 'Science',   hint: 'Makes tiny things look big' },
    { word: 'waterfall',  category: 'Nature',    hint: 'Water tumbling downward' },
    { word: 'desert',     category: 'Nature',    hint: 'Hot and very dry landscape' },
    { word: 'pirate',     category: 'Stories',   hint: 'Searches for treasure at sea' },
    { word: 'dragon',     category: 'Stories',   hint: 'Mythical creature that breathes fire' },
    { word: 'wizard',     category: 'Stories',   hint: 'Knows magical spells' },
    { word: 'knight',     category: 'Stories',   hint: 'Protects the castle' },
    { word: 'mermaid',    category: 'Stories',   hint: 'Half human, half fish' },
  ],
  expert: [
    { word: 'dolphin',        category: 'Animals',     hint: 'Intelligent sea mammal' },
    { word: 'chameleon',      category: 'Animals',     hint: 'Changes its colour' },
    { word: 'archaeologist',  category: 'Professions', hint: 'Digs up ancient artefacts' },
    { word: 'astronaut',      category: 'Professions', hint: 'Travels to outer space' },
    { word: 'conductor',      category: 'Professions', hint: 'Leads an orchestra' },
    { word: 'volcanologist',  category: 'Professions', hint: 'Studies volcanoes' },
    { word: 'photosynthesis', category: 'Science',     hint: 'How plants make food from light' },
    { word: 'equilibrium',    category: 'Science',     hint: 'Everything is perfectly balanced' },
    { word: 'earthworm',      category: 'Nature',      hint: 'Lives underground in the soil' },
    { word: 'paradise',       category: 'Nature',      hint: 'A place like heaven' },
    { word: 'expedition',     category: 'Adventure',   hint: 'A great journey of discovery' },
    { word: 'treasure',       category: 'Adventure',   hint: 'Pirates hide gold in this' },
    { word: 'labyrinth',      category: 'Adventure',   hint: 'A complicated maze' },
    { word: 'timemachine',    category: 'Adventure',   hint: 'It travels through time' },
    { word: 'planetarium',    category: 'Science',     hint: 'Building where you watch stars' },
  ],
};
